name: kazam
summary: Linux Screen Recorder, Broadcaster, Capture and OCR with AI in mind
description: |
     kazam is a versatile tool for screen recording, broadcasting, capturing and optical character recognition(OCR).
version: 2.0.0
base: core22
confinement: strict

parts:
  kazam:
    plugin: python
    source: .
    stage-packages:
      - python3-gst-1.0
      - gir1.2-wnck-3.0
      - gir1.2-gudev-1.0
      - gir1.2-keybinder-3.0
      - gnome-session-canberra # canberra-gtk-play
    python-packages:
      - kazam
    override-prime: |
      craftctl default
      sed -i 's|/usr/bin/canberra-gtk-play|canberra-gtk-play|g' lib/python3.10/site-packages/kazam/backend/grabber.py
      

  cleanup:
    after: [kazam]  # Make this part run last; list all your other parts here
    plugin: nil
    build-snaps: [gnome-42-2204]  # List all content-snaps you're using here
    override-prime: |
      set -eux
      for snap in "gnome-42-2204"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete


slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: org.kazam

apps:
  kazam:
    command: bin/kazam
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - audio-record
      - camera
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
    slots: [ dbus-svc ]
